In [3]:
import numpy as np
import torch
t= np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('rank of t:',t.ndim)
print('shape of t:', t.shape)
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2])




[0. 1. 2. 3. 4. 5. 6.]
rank of t: 1
shape of t: (7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.]


In [21]:
t= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,11]])
print(t)
print(t.ndim)
print(t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 11]]
2
(4, 3)


In [23]:
t= torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-2])
print(t[2:5])


1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(5.)
tensor([2., 3., 4.])


In [25]:
t= torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,11]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 11.]])


In [34]:
print(t.dim())
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])
print(t[:,:-1].size())

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
torch.Size([4, 2])


In [35]:
m1= torch.FloatTensor([[3,3]])
m2= torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 6.]])


In [36]:
m1= torch.FloatTensor([[1,2]])
m2= torch.FloatTensor([3])#3 ->[[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [37]:
m1 = torch.FloatTensor([[1,2]]) #1*2가 2*2로 늘어남
m2= torch.FloatTensor([[3],[4]]) #2*1이 2*2로 늘어남
print(m1+m2)


tensor([[4., 5.],
        [5., 6.]])


In [48]:
print('mul vs matmul')
m1= torch.FloatTensor([[1,2],[3,4]])
m2= torch.FloatTensor([[1],[2]])
print('matmul')#우리가 아는 행렬곱
print(m1.matmul(m2))
print('mul')#둘이 사이즈 맞추기 위해 broadcasting 함 즉 m2가 2*2로 브로드캐스팅 
print(m1.mul(m2))
print(m1*m2)


mul vs matmul
matmul
tensor([[ 5.],
        [11.]])
mul
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [43]:
t= torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [44]:
t= torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [47]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [56]:
print('max=말그대로 and argmax=인덱스값')
t= torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.max())
print(t.max(dim=0))#각값의 인덱스도 같이 반환
print('max:', t.max(dim=0)[0])
print('argmax:',t.max(dim=0)[1])

print(t.max(dim=1))
print('max:', t.max(dim=1)[0])
print('argmax:',t.max(dim=1)[1])



max=말그대로 and argmax=인덱스값
tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
max: tensor([3., 4.])
argmax: tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
max: tensor([2., 4.])
argmax: tensor([1, 1])


In [61]:
t= np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft= torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [63]:
#view 함수는 텐서의 형태를 바꾸는 함수
print(ft.view([-1,3]))#2*2*3 ->4*3 
#-1은 유동적인 값인 것 같음. 나머지 숫자에 따라 바뀌는 듯 위와 같은 상황에서는 두번째 차원이 3으로 정해졌으므로 자동으로 4가 됨
print(ft.view([-1,1,3]))#2*2*3 -> 4*1*3

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [67]:
#squeeze 함수는 뷰함수와 비슷함. but 디멘션값이 1인 것들을 모두 삭제해줌
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape
)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [69]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [71]:
#squeeze함수는 dim값을 넣어줌으로써 해당 dim에서 1삭제가능
print(ft.squeeze(dim=0))#아무것도 변하지 않음. 왜와이 dim=0은 3이니까
print(ft.squeeze(dim=1))#dim=1은 1이라 삭제

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


In [81]:
ft=torch.FloatTensor([[0,1,2],[3,4,5]])
print(ft)
print(ft.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
torch.Size([2, 3])


In [78]:
#unsqueeze함수는 원하는 디멘션값을 입력하면 그 자리에 1을 넣어줌. 디멘션값이 -1은 마지막 디멘션을 의미함. 리스트랑 비슷함.
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[[0., 1., 2.],
         [3., 4., 5.]]])
torch.Size([1, 2, 3])


In [79]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[[0., 1., 2.]],

        [[3., 4., 5.]]])
torch.Size([2, 1, 3])


In [82]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[[0.],
         [1.],
         [2.]],

        [[3.],
         [4.],
         [5.]]])
torch.Size([2, 3, 1])


In [6]:
#텐서를 타입캐스팅할 수 있음
lt=torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [4]:
bt=torch.ByteTensor([True,False,True,False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [5]:
print(bt.long())
print(bt.float())

tensor([1, 0, 1, 0])
tensor([1., 0., 1., 0.])


In [12]:
#concatenate 이어붙이기
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y],dim=0))#열로 갖다붙이기
print(torch.cat([x,y],dim=1))#행으로 갖다붙이기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [14]:
#stacking함수 
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
#위코드를 concatenate와 unsqueeze를 이용해서 구현하면
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
#unsqueeze를 이용해 벡터였던 xyz를 행렬로 만들고 쌓아줌


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [30]:
#ones and zeros 전부 0혹은 1로 채움
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [18]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [31]:
#in_place operation 새로운 메모리에 할당하지 않고 기존 값에 반영함
print(x.mul(2.))
print(x,end='\n\n')
print(x.mul_(2.))
print(x)

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
